import { useEffect, useRef, useState } from 'react';
import { Gauge, Wrench, CalendarClock, ClipboardList, Settings, Plus, RefreshCw, Cloud, CloudOff, Download, Upload, ChevronRight, Pencil, Trash2, Check, Paperclip, AlertCircle, Smartphone, CheckCircle2, Circle, X } from 'lucide-react';
import { DriveError, DriveStore, type DriveFile } from './drive';
import { authorize, loadGoogle } from './google';
import { ACTIONS, CATEGORIES, DUE_LABELS, formatDate, formatKm, maintenanceDue, newDocument, sortServices, todayISO, uid, validateDocument, type AppDocument, type Attachment, type FollowUp, type Schedule, type Service } from './model';
import { FollowUpForm, MileageForm, ScheduleForm, ServiceForm, VehicleForm } from './forms';
import { Badge, CarDrawing, Empty, Modal } from './ui';
import { useInstall } from './pwa';

const NAV = [{ id: 'dashboard', label: 'Overview', icon: Gauge }, { id: 'history', label: 'Service history', icon: Wrench }, { id: 'maintenance', label: 'Maintenance', icon: CalendarClock }, { id: 'followups', label: 'Follow-ups', icon: ClipboardList }, { id: 'settings', label: 'Settings', icon: Settings }] as const;
type View = typeof NAV[number]['id'];
type Dialog = { kind: 'service'; service?: Service } | { kind: 'schedule'; schedule?: Schedule } | { kind: 'followup'; followup?: FollowUp } | { kind: 'mileage' | 'vehicle' | 'import' | 'install' } | { kind: 'details'; service: Service } | { kind: 'attachment'; attachment: Attachment; url: string };
function initialView(): View { const query = new URLSearchParams(location.search).get('view'); return NAV.some(n => n.id === query) ? query as View : 'dashboard'; }
function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); }
function exportDoc(doc: AppDocument) { downloadBlob(new Blob([JSON.stringify(doc, null, 2)], { type: 'application/json' }), `sayarathy-${todayISO()}.json`); }
function upsert<T extends { id: string }>(items: T[], item: T): T[] { return items.some(i => i.id === item.id) ? items.map(i => i.id === item.id ? item : i) : [...items, item]; }

export default function App() {
  const [doc, setDoc] = useState<AppDocument>(newDocument);
  const savedDoc = useRef(doc);
  const [file, setFile] = useState<DriveFile | null>(null); const fileRef = useRef<DriveFile | null>(null);
  const [files, setFiles] = useState<DriveFile[]>([]);
  const [auth, setAuth] = useState<{ token: string; expiresAt: number } | null>(null);
  const [clientId, setClientId] = useState(import.meta.env.VITE_GOOGLE_CLIENT_ID || '');
  const [googleReady, setGoogleReady] = useState(false);
  const [online, setOnline] = useState(navigator.onLine);
  const [busy, setBusy] = useState(''); const busyRef = useRef(false);
  const [dirty, setDirty] = useState(false);
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [view, setView] = useState<View>(initialView);
  const [dialog, setDialog] = useState<Dialog | null>(null);
  const [confirmation, setConfirmation] = useState<{ title: string; text: string; action: () => Promise<void> } | null>(null);
  const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [reviewOnly, setReviewOnly] = useState(false);
  const [followupFilter, setFollowupFilter] = useState<'open' | 'done'>('open');
  const [syncedAt, setSyncedAt] = useState<string | null>(null);
  const install = useInstall();
  const canChange = !!auth && online && !busy && !dirty;
  const services = sortServices(doc.services);
  const dues = doc.schedules.map(schedule => ({ schedule, due: maintenanceDue(schedule, doc) }));
  const upcoming = dues.filter(d => !['unconfigured', 'unknown'].includes(d.due.status)).sort((a,b) => ({ overdue: 0, soon: 1, upcoming: 2, unknown: 3, unconfigured: 4 })[a.due.status] - ({ overdue: 0, soon: 1, upcoming: 2, unknown: 3, unconfigured: 4 })[b.due.status] || (a.due.remainingDays ?? Infinity) - (b.due.remainingDays ?? Infinity));
  const openFollowups = doc.followUps.filter(f => !f.done).sort((a,b) => (a.dueDate || '9999').localeCompare(b.dueDate || '9999'));
  const filteredServices = services.filter(s => (!category || s.items.some(i => i.category === category)) && (!reviewOnly || s.needsReview) && `${s.notes} ${s.items.map(i => `${i.description} ${CATEGORIES[i.category]}`).join(' ')}`.toLowerCase().includes(search.toLowerCase()));

  useEffect(() => { loadGoogle().then(() => setGoogleReady(true)).catch(e => setError(e.message)); }, []);
  useEffect(() => { window.scrollTo(0, 0); }, [view]);
  useEffect(() => {
    const update = () => setOnline(navigator.onLine); window.addEventListener('online', update); window.addEventListener('offline', update);
    const pop = () => setView(initialView()); window.addEventListener('popstate', pop);
    return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update); window.removeEventListener('popstate', pop); };
  }, []);
  useEffect(() => {
    if (!auth) return;
    const timer = setTimeout(() => { setAuth(null); setMessage('Google authorization expired. Reconnect to continue. Your open record stays in memory.'); }, Math.max(0, auth.expiresAt - Date.now() - 30000));
    return () => clearTimeout(timer);
  }, [auth]);
  useEffect(() => {
    const guard = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; window.addEventListener('beforeunload', guard);
    return () => window.removeEventListener('beforeunload', guard);
  }, [dirty]);
  useEffect(() => () => { if (dialog?.kind === 'attachment') URL.revokeObjectURL(dialog.url); }, [dialog]);

  function navigate(next: View) { setView(next); const url = new URL(location.href); url.searchParams.set('view', next); history.pushState({}, '', url); }
  function dataset(next: DriveFile | null) { fileRef.current = next; setFile(next); }
  function client() {
    if (!navigator.onLine) throw new Error('An internet connection is required. There are no offline saves or queued changes.');
    if (!auth || Date.now() >= auth.expiresAt - 30000) throw new Error('Reconnect Google Drive before saving.');
    return new DriveStore(auth.token);
  }
  async function execute(label: string, action: () => Promise<void>): Promise<boolean> {
    if (busyRef.current) return false;
    busyRef.current = true; setBusy(label); setError(''); setMessage('');
    try { await action(); return true; }
    catch(e) { setError(e instanceof Error ? e.message : 'The operation failed. Please retry.'); if (e instanceof DriveError && e.status === 401) setAuth(null); return false; }
    finally { busyRef.current = false; setBusy(''); }
  }
  async function loadFile(next: DriveFile, store: DriveStore) {
    const result = await store.read(next.id); const validated = validateDocument(result.data);
    dataset(result.file); setDoc(validated); savedDoc.current = validated; setDirty(false); setSyncedAt(new Date().toISOString());
  }
  function connect() {
    if (!online || !googleReady || !clientId.trim() || busyRef.current) return;
    const request = authorize(clientId.trim());
    void execute('Connecting to Google Drive', async () => {
      const next = await request; const store = new DriveStore(next.token); const found = await store.list();
      const editing = !!dialog && ['service', 'schedule', 'followup', 'mileage', 'vehicle', 'import'].includes(dialog.kind);
      if ((dirty || editing) && fileRef.current && !found.some(f => f.id === fileRef.current!.id)) throw new Error('Your unsaved draft belongs to a different or missing Drive file. Reconnect the original account, or download and discard the draft first.');
      setAuth(next); setFiles(found);
      if (!dirty && !editing) {
        const preferred = found.find(f => f.id === fileRef.current?.id) || (found.length === 1 ? found[0] : null);
        if (preferred) await loadFile(preferred, store);
        else { dataset(null); const fresh = newDocument(); setDoc(fresh); savedDoc.current = fresh; setSyncedAt(null); if (found.length > 1) { setView('settings'); setMessage('Choose the data file you want to open below.'); } }
      }
      setMessage(found.length ? 'Connected to Google Drive.' : 'Connected. Create your Camry log or restore your existing backup.');
    });
  }
  async function persist(next: AppDocument, store: DriveStore) {
    const validated = validateDocument({ ...next, updatedAt: new Date().toISOString() });
    setDoc(validated); setDirty(true);
    const text = JSON.stringify(validated, null, 2);
    if (new TextEncoder().encode(text).length > 3 * 1024 * 1024) throw new Error('The data file exceeds 3 MB. Export a backup before reducing its size.');
    const saved = fileRef.current ? await store.update(fileRef.current, text) : await store.create(text);
    dataset(saved); savedDoc.current = validated; setDirty(false); setSyncedAt(new Date().toISOString());
    setFiles(previous => [saved, ...previous.filter(f => f.id !== saved.id)]); setMessage('Saved to your Google Drive.');
  }
  async function mutate(next: AppDocument, label = 'Saving changes') {
    if (busyRef.current) return;
    const validated = validateDocument(next); setDoc(validated); setDirty(true);
    await execute(label, () => persist(validated, client()));
  }
  async function saveService(service: Service, uploads: File[]): Promise<boolean> {
    let staged = false;
    await execute('Saving service', async () => {
      const store = client(); const uploaded: Attachment[] = [];
      if (uploads.length && !fileRef.current) {
        const created = await store.create(JSON.stringify(doc)); dataset(created); savedDoc.current = doc;
      }
      try { for (const upload of uploads) uploaded.push(await store.uploadAttachment(fileRef.current!.id, upload)); }
      catch(e) { const cleanup = await Promise.allSettled(uploaded.map(a => store.delete(a.id))); if (cleanup.some(r => r.status === 'rejected')) throw new Error(`${(e as Error).message} Some incomplete uploads remain in your Sayarathy attachments folder.`); throw e; }
      const nextService = { ...service, attachments: [...service.attachments, ...uploaded] };
      const next = { ...doc, services: upsert(doc.services, nextService) };
      staged = true; await persist(next, store);
    });
    return staged;
  }
  function closeDialog() { setDialog(null); }
  function confirm(title: string, text: string, action: () => Promise<void>) { setConfirmation({ title, text, action }); }
  function deleteService(service: Service) { confirm('Delete service record?', 'This removes the visit and its linked follow-ups. Receipt and photo files remain in Google Drive so existing backups can still reference them.', async () => { await mutate({ ...doc, services: doc.services.filter(s => s.id !== service.id), followUps: doc.followUps.filter(f => f.serviceId !== service.id) }, 'Deleting service'); setDialog(null); }); }
  async function viewAttachment(attachment: Attachment, download = false) {
    await execute(download ? 'Downloading attachment' : 'Opening attachment', async () => { const blob = await client().downloadAttachment(attachment); if (download) downloadBlob(blob, attachment.name); else setDialog({ kind: 'attachment', attachment, url: URL.createObjectURL(blob) }); });
  }
  function newFollowup(serviceId: string | null = null) { setDialog({ kind: 'followup', followup: { id: uid(), title: '', serviceId, dueDate: null, done: false } }); }
  function serviceSummary(service: Service, compact = false) { return <button className={`service-summary ${compact ? 'compact' : ''}`} key={service.id} onClick={() => setDialog({ kind: 'details', service })}><div className="service-date"><strong>{formatDate(service.date)}</strong><span>{formatKm(service.odometerKm)}</span></div><div className="service-description"><h3>{service.items[0]?.description}{service.items.length > 1 && <small> +{service.items.length - 1} more</small>}</h3><p>{[...new Set(service.items.map(i => CATEGORIES[i.category]))].join(', ')}</p><div className="inline-tags">{service.needsReview && <Badge kind="soon">Needs clarification</Badge>}{service.attachments.length > 0 && <span className="attachment-count"><Paperclip size={12} />{service.attachments.length}</span>}</div></div><ChevronRight size={18} /></button>; }
  function dueRow(schedule: Schedule) {
    const due = maintenanceDue(schedule, doc);
    return <div className="maintenance-row" key={schedule.id}><div className={`maintenance-icon ${due.status}`}><Wrench size={18} /></div><div className="maintenance-content"><div className="row-title"><h3>{schedule.name}</h3><Badge kind={due.status}>{DUE_LABELS[due.status]}</Badge></div><p>{due.dueKm !== null ? formatKm(due.dueKm) : ''}{due.dueKm !== null && due.dueDate ? ' or ' : ''}{due.dueDate ? formatDate(due.dueDate) : ''}{due.status === 'unconfigured' ? 'Add an interval from your manual or mechanic.' : !due.dueKm && !due.dueDate ? 'Add a matching completed service or a baseline.' : ''}</p></div><button className="icon-button" aria-label={`Edit ${schedule.name} schedule`} disabled={!canChange} onClick={() => setDialog({ kind: 'schedule', schedule })}><Pencil size={17} /></button></div>;
  }
  function followupRow(f: FollowUp) { const overdue = !f.done && f.dueDate && f.dueDate <= todayISO(); return <div className={`followup-row ${f.done ? 'completed' : ''}`} key={f.id}><button className="icon-button" aria-label={f.done ? `Reopen ${f.title}` : `Complete ${f.title}`} disabled={!canChange} onClick={() => void mutate({ ...doc, followUps: doc.followUps.map(x => x.id === f.id ? { ...x, done: !x.done } : x) })}>{f.done ? <CheckCircle2 size={21} /> : <Circle size={21} />}</button><div><h3>{f.title}</h3><p>{f.dueDate ? `${overdue ? 'Due ' : 'Reminder: '}${formatDate(f.dueDate)}` : 'No reminder date'}{f.serviceId && ' · Linked to a service'}</p></div>{overdue && <Badge kind="overdue">Due</Badge>}<button className="icon-button" aria-label={`Edit follow-up ${f.title}`} disabled={!canChange} onClick={() => setDialog({ kind: 'followup', followup: f })}><Pencil size={16} /></button><button className="icon-button danger-text" aria-label={`Delete follow-up ${f.title}`} disabled={!canChange} onClick={() => confirm('Delete follow-up?', f.title, () => mutate({ ...doc, followUps: doc.followUps.filter(x => x.id !== f.id) }))}><Trash2 size={16} /></button></div>; }
  const common = { onClose: closeDialog, busy: !!busy, online: online && !!auth, onReconnect: connect };

  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="./" onClick={e => { e.preventDefault(); navigate('dashboard'); }}><span className="brand-icon">S</span><span>Sayarathy<small>Car maintenance</small></span></a><nav aria-label="Main navigation">{NAV.map(n => <button key={n.id} className={view === n.id ? 'active' : ''} onClick={() => navigate(n.id)} aria-current={view === n.id ? 'page' : undefined}><n.icon size={19} /><span>{n.label}</span>{n.id === 'followups' && openFollowups.length > 0 && <small>{openFollowups.length}</small>}</button>)}</nav><div className="sidebar-bottom"><div><Cloud size={20} /><p>Your Drive.<br /><strong>Your records.</strong></p></div>{!install.installed && <button className="install-link" onClick={() => install.available ? void install.install() : setDialog({ kind: 'install' })}><Smartphone size={17} />Install Sayarathy</button>}<a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a></div></aside>
    <div className="app-main"><header className="topbar"><a className="mobile-brand" href="./">Sayarathy</a><span className="topbar-vehicle">{doc.vehicle.make} {doc.vehicle.model} <span>{doc.vehicle.year}</span></span><div className="connection-controls"><span className={`connection ${auth && online ? 'connected' : ''}`}>{online ? <Cloud size={15} /> : <CloudOff size={15} />}<span>{!online ? 'Internet required' : busy || (dirty ? 'Unsaved changes' : file && auth ? 'Saved to Drive' : auth ? 'New log' : 'Drive disconnected')}</span></span>{auth && file && <button className="icon-button" aria-label="Reload from Google Drive" disabled={!!busy || dirty || !online} onClick={() => void execute('Reading from Drive', () => loadFile(file, client()))}><RefreshCw size={17} /></button>}{!auth && <button className="primary small" disabled={!online || !googleReady || !!busy || !clientId.trim()} onClick={connect}>Connect Drive</button>}</div></header>
    <main>
      {!online && <div className="notice offline" role="status"><CloudOff size={20} /><div><strong>You’re offline</strong><p>Sayarathy needs an internet connection. Saving, loading, and uploads are unavailable; changes are not queued.</p></div></div>}
      {error && <div className="notice error" role="alert"><AlertCircle size={20} /><div><strong>The operation did not finish</strong><p>{error}</p></div><button className="icon-button" aria-label="Dismiss error" onClick={() => setError('')}><X size={17} /></button></div>}
      {message && !error && <div className="message" role="status"><Check size={16} />{message}<button className="icon-button" aria-label="Dismiss message" onClick={() => setMessage('')}><X size={15} /></button></div>}
      {dirty && <div className="notice pending"><AlertCircle size={20} /><div><strong>Your changes have not been saved to Drive</strong><p>This draft is only in this open page. Retry saving, or download a copy before leaving.</p><div className="button-row"><button className="primary small" disabled={!online || !auth || !!busy} onClick={() => void mutate(doc, 'Retrying save')}>Retry save</button><button className="small" onClick={() => exportDoc(doc)}>Download draft</button><button className="text-button" disabled={!!busy} onClick={() => confirm('Discard unsaved changes?', 'The loaded Drive version will replace this in-memory draft. Any already uploaded attachments remain in Drive.', async () => { setDoc(savedDoc.current); setDirty(false); setError(''); })}>Discard draft</button></div></div></div>}
      {!auth && <div className="connect-banner"><div><h2>Your records stay in your Google Drive</h2><p>Connect to load your log, add a service, or save a change. No account with Sayarathy is needed.</p></div><button className="primary" disabled={!online || !googleReady || !!busy || !clientId.trim()} onClick={connect}>Connect Google Drive</button>{!googleReady && <button className="text-button" disabled={!!busy} onClick={() => loadGoogle().then(() => setGoogleReady(true)).catch(e => setError(e.message))}>Retry Google authorization</button>}</div>}
      {auth && !file && !dirty && <div className="notice"><Cloud size={20} /><div><strong>Start your Camry log</strong><p>Create an empty log in Drive, or restore a backup from Settings.</p></div><button className="primary small" disabled={!canChange} onClick={() => void mutate(doc, 'Creating your log')}>Create my log</button></div>}
      <div className="page-heading"><div><h1>{view === 'dashboard' ? 'Your car, at a glance.' : NAV.find(n => n.id === view)?.label}</h1><p>{view === 'dashboard' ? 'A little history makes the next service clearer.' : view === 'history' ? 'Every visit, repair, and replacement in one place.' : view === 'maintenance' ? 'Your manual or mechanic sets the intervals. We do the calculations.' : view === 'followups' ? 'Keep mechanic advice and unfinished issues in sight.' : 'Your vehicle, Google Drive connection, and backups.'}</p></div>{(view === 'dashboard' || view === 'history') && <button className="primary" disabled={!canChange} onClick={() => setDialog({ kind: 'service' })}><Plus size={18} />Add service</button>}{view === 'maintenance' && <button className="primary" disabled={!canChange} onClick={() => setDialog({ kind: 'schedule' })}><Plus size={18} />Add schedule</button>}{view === 'followups' && <button className="primary" disabled={!canChange} onClick={() => newFollowup()}><Plus size={18} />Add follow-up</button>}</div>

      {view === 'dashboard' && <>
        <section className="vehicle-overview"><div><p>{doc.vehicle.make} · {doc.vehicle.year}</p><h2>{doc.vehicle.model}</h2><div className="vehicle-specs">{doc.vehicle.fuel || 'Fuel type not set'}{doc.vehicle.engine && ` · ${doc.vehicle.engine}`}</div><div className="mileage-display"><span>Current odometer</span><strong>{doc.vehicle.odometerKm === null ? 'Add your reading' : formatKm(doc.vehicle.odometerKm)}</strong><small>{doc.vehicle.odometerDate ? `Recorded ${formatDate(doc.vehicle.odometerDate)}` : 'Historical service mileage is not a current reading.'}</small></div><button className="vehicle-action" disabled={!canChange} onClick={() => setDialog({ kind: 'mileage' })}><Gauge size={16} />Update mileage</button></div><CarDrawing /></section>
        <div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>Next maintenance</h2><button className="text-button" onClick={() => navigate('maintenance')}>View schedule<ChevronRight size={15} /></button></div>{upcoming.length > 0 ? <><div className="maintenance-counts"><span><strong>{dues.filter(d => d.due.status === 'overdue').length}</strong> due now</span><span><strong>{dues.filter(d => d.due.status === 'soon').length}</strong> due soon</span><span><strong>{dues.filter(d => d.due.status === 'upcoming').length}</strong> upcoming</span></div>{upcoming.slice(0, 4).map(({ schedule }) => dueRow(schedule))}</> : <Empty title="Set your maintenance intervals" action={<button onClick={() => navigate('maintenance')}>Configure schedules</button>}>Add distance or time intervals from your manual or mechanic to see what is due next.</Empty>}{dues.some(d => d.due.missing.length > 0) && <p className="panel-footnote">Some reminders need mileage or a last-completion baseline. Check Maintenance for details.</p>}</section><section className="panel"><div className="section-heading"><h2>Recent services</h2><button className="text-button" onClick={() => navigate('history')}>View history<ChevronRight size={15} /></button></div>{services.length ? services.slice(0, 3).map(s => serviceSummary(s, true)) : <Empty title="Your history starts here">Add your first service or restore your existing records from Settings.</Empty>}</section></div>
        <section className="panel followup-panel"><div className="section-heading"><h2>Open follow-ups <span className="count">{openFollowups.length}</span></h2><button className="text-button" onClick={() => navigate('followups')}>View all<ChevronRight size={15} /></button></div>{openFollowups.length ? openFollowups.slice(0, 3).map(followupRow) : <p className="quiet-empty"><CheckCircle2 size={18} />No open follow-ups. Add one when your mechanic recommends a check or repair.</p>}</section>
        {services.some(s => s.needsReview) && <button className="review-callout" onClick={() => { setReviewOnly(true); navigate('history'); }}><AlertCircle size={18} /><span>{services.filter(s => s.needsReview).length} service records need clarification</span><ChevronRight size={17} /></button>}
      </>}

      {view === 'history' && <><div className="history-filters"><label><span className="sr-only">Search service history</span><input type="search" aria-label="Search service history" value={search} placeholder="Search work or notes…" onChange={e => setSearch(e.target.value)} /></label><label><span className="sr-only">Filter category</span><select aria-label="Filter category" value={category} onChange={e => setCategory(e.target.value)}><option value="">All categories</option>{Object.entries(CATEGORIES).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={reviewOnly} onChange={e => setReviewOnly(e.target.checked)} />Needs clarification</label></div><p className="result-count">{filteredServices.length} {filteredServices.length === 1 ? 'visit' : 'visits'}</p>{filteredServices.length ? <div className="history-list">{filteredServices.map((s, i) => <div key={s.id}>{(i === 0 || s.date.slice(0,4) !== filteredServices[i-1].date.slice(0,4)) && <h2 className="year-heading">{s.date.slice(0,4)}</h2>}{serviceSummary(s)}</div>)}</div> : <div className="panel"><Empty title={services.length ? 'No matching services' : 'No service records yet'}>{services.length ? 'Try another search or category.' : 'Add your first service to start the timeline.'}</Empty></div>}</>}

      {view === 'maintenance' && <><div className="schedule-explainer"><CalendarClock size={21} /><p>Reminders use the last service with the same category and work type. If you set both time and distance, <strong>whichever comes first</strong> applies. Intervals are not manufacturer recommendations.</p></div>{doc.schedules.length ? <div className="schedule-list">{dues.map(({ schedule, due }) => <section className="panel schedule-card" key={schedule.id}><div className="section-heading"><h2>{schedule.name}</h2><Badge kind={due.status}>{DUE_LABELS[due.status]}</Badge></div><div className="schedule-meta"><span>{CATEGORIES[schedule.category]}</span><span>{ACTIONS[schedule.action]}</span></div><div className="schedule-due"><div><span>Next distance target</span><strong>{due.dueKm !== null ? formatKm(due.dueKm) : 'Not available'}</strong>{due.remainingKm !== null && <small>{due.remainingKm > 0 ? `${due.remainingKm.toLocaleString()} km remaining` : `${Math.abs(due.remainingKm).toLocaleString()} km past target`}</small>}</div><div><span>Next date target</span><strong>{due.dueDate ? formatDate(due.dueDate) : 'Not available'}</strong>{due.remainingDays !== null && <small>{due.remainingDays > 0 ? `${due.remainingDays} days remaining` : `${Math.abs(due.remainingDays)} days past target`}</small>}</div></div><p className="help">Interval: {schedule.intervalKm ? formatKm(schedule.intervalKm) : 'Distance not set'}{schedule.intervalMonths ? ` / ${schedule.intervalMonths} months` : ' / Time not set'}<br />Last completed: {due.last.date ? formatDate(due.last.date) : 'No matching completion'}{due.last.km !== null ? ` at ${formatKm(due.last.km)}` : ''}</p>{due.missing.length > 0 && <ul className="missing-data">{due.missing.map(m => <li key={m}>{m}</li>)}</ul>}<div className="card-actions"><button disabled={!canChange} onClick={() => setDialog({ kind: 'schedule', schedule })}><Pencil size={15} />Edit schedule</button><button className="icon-button danger-text" aria-label={`Delete ${schedule.name} schedule`} disabled={!canChange} onClick={() => confirm('Delete maintenance schedule?', 'This removes the reminder rule, not the service history.', () => mutate({ ...doc, schedules: doc.schedules.filter(x => x.id !== schedule.id) }))}><Trash2 size={16} /></button></div></section>)}</div> : <section className="panel"><Empty title="No maintenance schedules">Add a rule using the interval you know from your manual or mechanic.</Empty></section>}</>}

      {view === 'followups' && <section className="panel"><div className="tabs" aria-label="Follow-up status"><button className={followupFilter === 'open' ? 'active' : ''} onClick={() => setFollowupFilter('open')}>Open ({openFollowups.length})</button><button className={followupFilter === 'done' ? 'active' : ''} onClick={() => setFollowupFilter('done')}>Completed ({doc.followUps.filter(f => f.done).length})</button></div>{doc.followUps.filter(f => followupFilter === 'done' ? f.done : !f.done).length ? doc.followUps.filter(f => followupFilter === 'done' ? f.done : !f.done).map(followupRow) : <Empty title={followupFilter === 'done' ? 'No completed follow-ups' : 'Nothing to follow up yet'}>Use follow-ups for mechanic advice, issues to monitor, or repairs you want to arrange.</Empty>}</section>}

      {view === 'settings' && <div className="settings-grid"><section className="panel"><div className="section-heading"><h2>Your vehicle</h2><button className="text-button" disabled={!canChange} onClick={() => setDialog({ kind: 'vehicle' })}><Pencil size={15} />Edit</button></div><dl className="details-list"><div><dt>Vehicle</dt><dd>{doc.vehicle.make} {doc.vehicle.model}, {doc.vehicle.year}</dd></div><div><dt>Fuel / engine</dt><dd>{doc.vehicle.fuel || 'Not specified'}{doc.vehicle.engine && ` / ${doc.vehicle.engine}`}</dd></div><div><dt>Current mileage</dt><dd>{formatKm(doc.vehicle.odometerKm)}</dd></div><div><dt>Due-soon threshold</dt><dd>{doc.settings.dueSoonKm.toLocaleString()} km or {doc.settings.dueSoonDays} days</dd></div></dl><button disabled={!canChange} onClick={() => setDialog({ kind: 'mileage' })}><Gauge size={16} />Update mileage</button><details className="mileage-history"><summary>Mileage readings ({doc.mileage.length})</summary>{doc.mileage.length ? [...doc.mileage].sort((a,b) => b.date.localeCompare(a.date)).map(m => <div key={m.id}><span>{formatDate(m.date)}</span><strong>{formatKm(m.odometerKm)}</strong></div>) : <p className="help">No current-mileage readings recorded yet.</p>}</details></section>
        <section className="panel"><div className="section-heading"><h2>Google Drive</h2><Badge kind={auth ? 'upcoming' : ''}>{auth ? 'Connected' : 'Disconnected'}</Badge></div><p className="help">{file ? `Data file: ${file.name}` : 'No data file loaded.'}{syncedAt && <><br />Last saved or loaded: {new Date(syncedAt).toLocaleString()}</>}</p><div className="button-row">{auth ? <><button disabled={!online || !!busy || dirty} onClick={() => void execute('Refreshing Drive files', async () => setFiles(await client().list()))}><RefreshCw size={16} />Refresh files</button><button disabled={!!busy || dirty} onClick={() => { setAuth(null); setFiles([]); dataset(null); const fresh = newDocument(); setDoc(fresh); savedDoc.current = fresh; setSyncedAt(null); setMessage('Disconnected locally. Google permission remains granted; manage it in your Google account.'); }}>Disconnect</button></> : <button className="primary" disabled={!googleReady || !online || !!busy || !clientId.trim()} onClick={connect}>Connect Google Drive</button>}</div>{files.map(f => <div className="cloud-file" key={f.id}><span><strong>{f.name}</strong><small>{f.modifiedTime ? new Date(f.modifiedTime).toLocaleString() : ''}</small></span><button className="small" disabled={!auth || !!busy || dirty || !online} onClick={() => void execute('Opening Drive file', () => loadFile(f, client()))}>{file?.id === f.id ? 'Reload' : 'Open'}</button><button className="icon-button" aria-label={`Download original ${f.name}`} disabled={!auth || !!busy || !online} onClick={() => void execute('Downloading original file', async () => { const original = await client().read(f.id); downloadBlob(new Blob([JSON.stringify(original.data, null, 2)], { type: 'application/json' }), f.name); })}><Download size={16} /></button></div>)}<details className="advanced"><summary>Connection configuration</summary><label>Google OAuth client ID<input value={clientId} disabled={!!auth || !!busy} onChange={e => setClientId(e.target.value)} /></label><p className="help">Public app configuration, not a password. No secret is stored in this app.</p></details></section>
        <section className="panel"><h2>Backup & restore</h2><p className="help">Export your complete log as JSON. Receipts stay in Drive; the backup includes their file references, not the files themselves.</p><div className="button-row"><button onClick={() => exportDoc(doc)}><Download size={16} />Export JSON backup</button><button disabled={!canChange} onClick={() => setDialog({ kind: 'import' })}><Upload size={16} />Restore backup</button></div><p className="help">A restore replaces this log’s vehicle, services, schedules, follow-ups, and mileage history after you confirm.</p></section>
        <section className="panel"><h2>Install Sayarathy</h2><p className="help">Open it from your home screen in its own window. Internet is required; there is no offline mode, cached log, or background sync.</p><button onClick={() => install.available ? void install.install() : setDialog({ kind: 'install' })} disabled={install.installed}><Smartphone size={16} />{install.installed ? 'Running as an installed app' : 'Install or view instructions'}</button><p className="help">Maintenance reminders appear when you open the app. There are no background push notifications.</p></section></div>}
      <footer><span>Sayarathy · Your records belong to you.</span><div><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a><a href="mailto:ammarabz10@gmail.com">Contact</a></div></footer>
    </main></div>

    {dialog?.kind === 'service' && <ServiceForm {...common} initial={dialog.service} onSave={saveService} />}
    {dialog?.kind === 'schedule' && <ScheduleForm {...common} initial={dialog.schedule} onSave={async schedule => mutate({ ...doc, schedules: upsert(doc.schedules, schedule) })} />}
    {dialog?.kind === 'followup' && <FollowUpForm {...common} initial={dialog.followup} services={services} onSave={async followup => mutate({ ...doc, followUps: upsert(doc.followUps, followup) })} />}
    {dialog?.kind === 'mileage' && <MileageForm {...common} doc={doc} onSave={async (km, date) => mutate({ ...doc, vehicle: { ...doc.vehicle, odometerKm: km, odometerDate: date }, mileage: [...doc.mileage, { id: uid(), date, odometerKm: km }] })} />}
    {dialog?.kind === 'vehicle' && <VehicleForm {...common} doc={doc} onSave={async next => mutate(next)} />}
    {dialog?.kind === 'import' && <ImportDialog {...common} replacing={!!file} onRestore={async next => mutate(next, 'Restoring backup')} />}
    {dialog?.kind === 'install' && <Modal title="Install Sayarathy" onClose={closeDialog}><div className="modal-body"><Smartphone size={32} /><p>Add Sayarathy to your home screen for a dedicated app window.</p><h3>Android / Chrome</h3><p>Open the browser menu and choose <strong>Install app</strong> or <strong>Add to home screen</strong>. If an install button is available in Sayarathy, you can use that too.</p><h3>iPhone / iPad</h3><p>Open this site in Safari, tap <strong>Share</strong>, then <strong>Add to Home Screen</strong>. Keep <strong>Open as Web App</strong> enabled if shown.</p><h3>Desktop</h3><p>Use the install icon in Chrome or Edge’s address bar, or the browser’s install-app menu.</p><p className="help">Installation availability depends on your browser. An internet connection is always required.</p></div></Modal>}
    {dialog?.kind === 'details' && <Modal title={formatDate(dialog.service.date)} onClose={closeDialog} wide><div className="modal-body service-details"><div className="detail-meta"><Badge>{formatKm(dialog.service.odometerKm)}</Badge>{dialog.service.needsReview && <Badge kind="soon">Needs clarification</Badge>}</div><h3>Work completed</h3>{dialog.service.items.map(i => <div className="detail-work" key={i.id}><CheckCircle2 size={16} /><div><strong>{i.description}</strong><small>{CATEGORIES[i.category]} · {ACTIONS[i.action]}</small></div></div>)}{dialog.service.notes && <><h3>Notes</h3><p className="preserve-lines">{dialog.service.notes}</p></>}{dialog.service.attachments.length > 0 && <><h3>Receipts & photos</h3>{dialog.service.attachments.map(a => <div className="attachment-row" key={a.id}><button className="text-button" disabled={!auth || !online || !!busy} onClick={() => void viewAttachment(a)}><Paperclip size={16} />{a.name}</button><button className="icon-button" aria-label={`Download ${a.name}`} disabled={!auth || !online || !!busy} onClick={() => void viewAttachment(a, true)}><Download size={16} /></button></div>)}</>}<div className="button-row"><button disabled={!canChange} onClick={() => setDialog({ kind: 'service', service: dialog.service })}><Pencil size={16} />Edit service</button><button disabled={!canChange} onClick={() => newFollowup(dialog.service.id)}><Plus size={16} />Add follow-up</button><button className="danger-text" disabled={!canChange} onClick={() => deleteService(dialog.service)}><Trash2 size={16} />Delete record</button></div></div></Modal>}
    {dialog?.kind === 'attachment' && <Modal title={dialog.attachment.name} onClose={closeDialog} wide><div className="modal-body">{dialog.attachment.mimeType.startsWith('image/') ? <img className="attachment-preview" src={dialog.url} alt={dialog.attachment.name} /> : <object className="pdf-preview" data={dialog.url} type="application/pdf"><p>Your browser cannot preview this PDF. Use Download below.</p></object>}<button onClick={() => { const a = document.createElement('a'); a.href = dialog.url; a.download = dialog.attachment.name; a.click(); }}><Download size={16} />Download file</button></div></Modal>}
    {confirmation && <Modal title={confirmation.title} onClose={() => setConfirmation(null)} busy={!!busy}><div className="modal-body"><p>{confirmation.text}</p><div className="form-actions"><button disabled={!!busy} onClick={() => setConfirmation(null)}>Cancel</button><button className="danger" disabled={!!busy} onClick={() => { const action = confirmation.action; setConfirmation(null); void action(); }}>Confirm</button></div></div></Modal>}
  </div>;
}

function ImportDialog({ onClose, busy, online, replacing, onRestore }: { onClose: () => void; busy: boolean; online: boolean; replacing: boolean; onRestore: (doc: AppDocument) => Promise<void> }) {
  const [text, setText] = useState(''); const [error, setError] = useState(''); const [preview, setPreview] = useState<AppDocument | null>(null); const [confirmed, setConfirmed] = useState(false);
  const parse = (value: string) => { setText(value); setPreview(null); setError(''); setConfirmed(false); try { if (new TextEncoder().encode(value).length > 3 * 1024 * 1024) throw new Error('Backups must be at most 3 MB.'); setPreview(validateDocument(JSON.parse(value))); } catch(e) { if (value.trim()) setError((e as Error).message); } };
  return <Modal title="Restore JSON backup" onClose={onClose} busy={busy}><div className="modal-body"><p>Choose a Sayarathy backup, or paste its JSON. Check the summary before restoring.</p><label className="file-picker">Choose JSON backup<input type="file" accept=".json,application/json" disabled={busy} onChange={e => { const f = e.target.files?.[0]; if (!f) return; if (f.size > 3 * 1024 * 1024) { setError('Backups must be at most 3 MB.'); return; } f.text().then(parse).catch(() => setError('Could not read the selected file.')); }} /></label><label>Backup JSON<textarea rows={7} spellCheck={false} value={text} disabled={busy} onChange={e => parse(e.target.value)} /></label>{error && <p className="form-error" role="alert">{error}</p>}{preview && <div className="import-summary"><strong>{preview.vehicle.make} {preview.vehicle.model}, {preview.vehicle.year}</strong><p>{preview.services.length} services · {preview.schedules.length} schedules · {preview.followUps.length} follow-ups</p><label className="checkbox-label"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />{replacing ? 'Replace my current log with this backup' : 'Create my Drive log from this backup'}</label></div>}<div className="form-actions"><button disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={!preview || !confirmed || busy || !online} onClick={async () => { if (!preview) return; await onRestore(preview); onClose(); }}>{busy ? 'Restoring…' : 'Restore backup'}</button></div></div></Modal>;
}
