import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Plus, Trash2, Paperclip } from 'lucide-react';
import { ACTIONS, CATEGORIES, isDate, numericInput, todayISO, uid, validateDocument, type AppDocument, type FollowUp, type Schedule, type Service } from './model';
import { Modal } from './ui';

type Common = { onClose: () => void; busy: boolean; online: boolean; onReconnect?: () => void };
function useLeaveWarning(value: unknown) {
  const baseline = useRef(JSON.stringify(value)); const dirty = JSON.stringify(value) !== baseline.current;
  useEffect(() => { const guard = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
}
function ErrorMessage({ error }: { error: string }) { return error ? <p className="form-error" role="alert">{error}</p> : null; }
function Buttons({ onClose, busy, online, label, onReconnect }: Common & { label: string }) { return <div className="form-actions">{!online && navigator.onLine && onReconnect && <button type="button" disabled={busy} onClick={onReconnect}>Reconnect Drive</button>}<button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy || !online} type="submit">{busy ? 'Saving…' : label}</button></div>; }

export function ServiceForm({ initial, onSave, ...common }: Common & { initial?: Service; onSave: (service: Service, uploads: File[]) => Promise<boolean> }) {
  const [service, setService] = useState<Service>(() => initial ? structuredClone(initial) : { id: uid(), date: todayISO(), odometerKm: null, notes: '', attachments: [], needsReview: false, items: [{ id: uid(), category: 'oil', action: 'replace', description: '' }] });
  const [mileage, setMileage] = useState(initial?.odometerKm?.toString() || '');
  const [uploads, setUploads] = useState<File[]>([]);
  const [error, setError] = useState('');
  useLeaveWarning({ service, mileage, uploads: uploads.map(f => `${f.name}:${f.size}`) });
  async function submit(e: FormEvent) {
    e.preventDefault(); setError('');
    try {
      if (!isDate(service.date) || service.date > todayISO()) throw new Error('Enter a valid service date that is not in the future.');
      if (!service.items.length || service.items.some(i => !i.description.trim())) throw new Error('Describe every completed work item.');
      if (service.attachments.length + uploads.length > 20) throw new Error('A service can have up to 20 attachments.');
      const km = numericInput(mileage, 'Service mileage');
      if (await onSave({ ...service, odometerKm: km, items: service.items.map(i => ({ ...i, description: i.description.trim() })) }, uploads)) common.onClose();
      else setError('The service could not be saved. Check the connection message and retry.');
    } catch (e) { setError((e as Error).message); }
  }
  const updateItem = (id: string, patch: Partial<Service['items'][number]>) => setService(s => ({ ...s, items: s.items.map(i => i.id === id ? { ...i, ...patch } : i) }));
  return <Modal title={initial ? 'Edit service' : 'Add a service'} {...common} wide><form onSubmit={submit}><fieldset disabled={common.busy}><div className="form-grid"><label>Service date<input required type="date" max={todayISO()} value={service.date} onChange={e => setService({ ...service, date: e.target.value })} /></label><label>Odometer (km)<input type="number" min="0" max="5000000" step="1" placeholder="Leave blank if unknown" value={mileage} onChange={e => setMileage(e.target.value)} /></label></div><div className="form-section-heading"><h3>Work completed</h3><button type="button" className="text-button" onClick={() => setService({ ...service, items: [...service.items, { id: uid(), description: '', category: 'other', action: 'other' }] })}><Plus size={16} />Add work item</button></div>
    <div className="work-items">{service.items.map((item, index) => <div className="work-item" key={item.id}><label className="work-description">Description<input required maxLength={1000} aria-label={`Work description ${index + 1}`} placeholder="e.g. Engine oil 20W50, 4L" value={item.description} onChange={e => updateItem(item.id, { description: e.target.value })} /></label><div className="form-grid item-options"><label>Category<select aria-label={`Work category ${index + 1}`} value={item.category} onChange={e => updateItem(item.id, { category: e.target.value as typeof item.category })}>{Object.entries(CATEGORIES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Work type<select aria-label={`Work type ${index + 1}`} value={item.action} onChange={e => updateItem(item.id, { action: e.target.value as typeof item.action })}>{Object.entries(ACTIONS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button type="button" className="icon-button danger-text" aria-label={`Remove work item ${index + 1}`} disabled={service.items.length === 1} onClick={() => setService({ ...service, items: service.items.filter(i => i.id !== item.id) })}><Trash2 size={17} /></button></div></div>)}</div>
    <p className="help">Only work with the matching category and work type resets a maintenance schedule. Repairs and inspections do not count as replacements.</p><label>Notes<textarea maxLength={10000} rows={3} placeholder="Mechanic advice, original descriptions, or details to remember" value={service.notes} onChange={e => setService({ ...service, notes: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={service.needsReview} onChange={e => setService({ ...service, needsReview: e.target.checked })} />This record needs clarification</label>
    <div className="form-section-heading"><h3>Receipts & photos</h3><Paperclip size={17} /></div><p className="help">Private Google Drive files. PDF, JPG, PNG, or WebP, up to 10 MB each. Removing a saved attachment here unlinks it; the original stays in Drive.</p>{service.attachments.map(a => <div className="attachment-row" key={a.id}><span>{a.name}</span><button type="button" className="text-button danger-text" onClick={() => setService({ ...service, attachments: service.attachments.filter(x => x.id !== a.id) })}>Remove from record</button></div>)}<label className="file-picker">Choose receipts or photos<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e => { const next = [...(e.target.files || [])]; if (next.some(f => f.size > 10 * 1024 * 1024 || f.size === 0 || !['application/pdf', 'image/jpeg', 'image/png', 'image/webp'].includes(f.type))) { setError('Choose PDF, JPG, PNG, or WebP files between 1 byte and 10 MB.'); e.target.value = ''; return; } setUploads(prev => [...prev, ...next]); e.target.value = ''; }} /></label>{uploads.map((f, i) => <div className="attachment-row" key={`${f.name}-${i}`}><span>{f.name} <small>Ready to upload</small></span><button type="button" className="text-button" onClick={() => setUploads(uploads.filter((_, index) => index !== i))}>Remove</button></div>)}</fieldset><ErrorMessage error={error} /><Buttons {...common} label={initial ? 'Save changes' : 'Save service'} /></form></Modal>;
}

export function ScheduleForm({ initial, onSave, ...common }: Common & { initial?: Schedule; onSave: (schedule: Schedule) => Promise<void> }) {
  const [s, setS] = useState<Schedule>(initial || { id: uid(), name: '', category: 'oil', action: 'replace', intervalKm: null, intervalMonths: null, baselineDate: null, baselineKm: null });
  const [km, setKm] = useState(initial?.intervalKm?.toString() || ''); const [months, setMonths] = useState(initial?.intervalMonths?.toString() || ''); const [baselineKm, setBaselineKm] = useState(initial?.baselineKm?.toString() || ''); const [error, setError] = useState('');
  useLeaveWarning({ s, km, months, baselineKm });
  async function submit(e: FormEvent) { e.preventDefault(); try { const intervalKm = numericInput(km, 'Distance interval'); const intervalMonths = numericInput(months, 'Month interval', 1200); if (intervalKm === 0 || intervalMonths === 0) throw new Error('Intervals must be greater than zero, or left blank.'); if (!s.name.trim()) throw new Error('Enter a schedule name.'); if (s.baselineDate && (!isDate(s.baselineDate) || s.baselineDate > todayISO())) throw new Error('The last completion date must be valid and not in the future.'); const baselineMileage = numericInput(baselineKm, 'Baseline mileage'); if (baselineMileage !== null && !s.baselineDate) throw new Error('Add a baseline date when entering a baseline mileage.'); await onSave({ ...s, name: s.name.trim(), intervalKm, intervalMonths, baselineKm: baselineMileage }); common.onClose(); } catch(e) { setError((e as Error).message); } }
  return <Modal title={initial ? 'Edit maintenance schedule' : 'Add maintenance schedule'} {...common}><form onSubmit={submit}><fieldset disabled={common.busy}><label>Maintenance item<input required maxLength={200} value={s.name} onChange={e => setS({ ...s, name: e.target.value })} /></label><div className="form-grid"><label>Matching category<select value={s.category} onChange={e => setS({ ...s, category: e.target.value as Schedule['category'] })}>{Object.entries(CATEGORIES).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label><label>Matching work type<select value={s.action} onChange={e => setS({ ...s, action: e.target.value as Schedule['action'] })}>{Object.entries(ACTIONS).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></label></div><h3>Interval from your manual or mechanic</h3><div className="form-grid"><label>Every (km)<input type="number" min="1" max="5000000" value={km} placeholder="Optional" onChange={e => setKm(e.target.value)} /></label><label>Every (months)<input type="number" min="1" max="1200" value={months} placeholder="Optional" onChange={e => setMonths(e.target.value)} /></label></div><p className="help">When both are set, whichever comes first determines when it is due. Leave both blank until you confirm the interval.</p><h3>Optional last-completion baseline</h3><p className="help">Use this for work not in your history. A newer matching service takes precedence over this baseline.</p><div className="form-grid"><label>Last completed date<input type="date" max={todayISO()} value={s.baselineDate || ''} onChange={e => setS({ ...s, baselineDate: e.target.value || null })} /></label><label>Last completed mileage (km)<input type="number" min="0" value={baselineKm} placeholder="Optional" onChange={e => setBaselineKm(e.target.value)} /></label></div></fieldset><ErrorMessage error={error} /><Buttons {...common} label="Save schedule" /></form></Modal>;
}

export function FollowUpForm({ initial, services, onSave, ...common }: Common & { initial?: FollowUp; services: Service[]; onSave: (followUp: FollowUp) => Promise<void> }) {
  const [f, setF] = useState<FollowUp>(initial || { id: uid(), title: '', dueDate: null, serviceId: null, done: false }); const [error, setError] = useState('');
  useLeaveWarning(f);
  async function submit(e: FormEvent) { e.preventDefault(); try { if (!f.title.trim()) throw new Error('Describe the issue or follow-up.'); if (f.dueDate && !isDate(f.dueDate)) throw new Error('Enter a valid reminder date.'); await onSave({ ...f, title: f.title.trim() }); common.onClose(); } catch(e) { setError((e as Error).message); } }
  return <Modal title={initial ? 'Edit follow-up' : 'Add a follow-up'} {...common}><form onSubmit={submit}><fieldset disabled={common.busy}><label>Issue or mechanic advice<textarea required rows={3} maxLength={2000} placeholder="e.g. Monitor for another engine oil leak" value={f.title} onChange={e => setF({ ...f, title: e.target.value })} /></label><label>Reminder date<input type="date" value={f.dueDate || ''} onChange={e => setF({ ...f, dueDate: e.target.value || null })} /></label><label>Related service<select value={f.serviceId || ''} onChange={e => setF({ ...f, serviceId: e.target.value || null })}><option value="">No linked service</option>{services.map(s => <option key={s.id} value={s.id}>{s.date} · {s.items[0]?.description}</option>)}</select></label></fieldset><ErrorMessage error={error} /><Buttons {...common} label="Save follow-up" /></form></Modal>;
}

export function MileageForm({ doc, onSave, ...common }: Common & { doc: AppDocument; onSave: (km: number, date: string) => Promise<void> }) {
  const [km, setKm] = useState(''); const [date, setDate] = useState(todayISO()); const [error, setError] = useState('');
  useLeaveWarning({ km, date });
  const highest = Math.max(0, doc.vehicle.odometerKm || 0, ...doc.services.map(s => s.odometerKm || 0), ...doc.mileage.map(m => m.odometerKm));
  async function submit(e: FormEvent) { e.preventDefault(); try { const n = numericInput(km, 'Current mileage'); if (n === null) throw new Error('Enter your current odometer reading.'); if (n < highest) throw new Error(`This is below a recorded reading of ${highest.toLocaleString()} km. Correct the older record first if it is incorrect.`); if (!isDate(date) || date > todayISO() || (doc.vehicle.odometerDate && date < doc.vehicle.odometerDate)) throw new Error('Choose a valid date no earlier than your current mileage reading and no later than today.'); await onSave(n, date); common.onClose(); } catch(e) { setError((e as Error).message); } }
  return <Modal title="Update mileage" {...common}><form onSubmit={submit}><fieldset disabled={common.busy}><p className="help">This is your current odometer reading, not a past service mileage. It is used to calculate distance-based reminders.</p><label>Current odometer (km)<input required type="number" min={highest} max="5000000" placeholder={highest ? `At least ${highest.toLocaleString()} km` : 'Enter mileage'} value={km} onChange={e => setKm(e.target.value)} /></label><label>Reading date<input required type="date" max={todayISO()} value={date} onChange={e => setDate(e.target.value)} /></label></fieldset><ErrorMessage error={error} /><Buttons {...common} label="Save mileage" /></form></Modal>;
}

export function VehicleForm({ doc, onSave, ...common }: Common & { doc: AppDocument; onSave: (doc: AppDocument) => Promise<void> }) {
  const [v, setV] = useState(doc.vehicle); const [year, setYear] = useState(v.year.toString()); const [days, setDays] = useState(doc.settings.dueSoonDays.toString()); const [km, setKm] = useState(doc.settings.dueSoonKm.toString()); const [error, setError] = useState('');
  useLeaveWarning({ v, year, days, km });
  async function submit(e: FormEvent) { e.preventDefault(); try { const next = { ...doc, vehicle: { ...v, year: numericInput(year, 'Vehicle year', new Date().getFullYear() + 1)! }, settings: { dueSoonKm: numericInput(km, 'Due-soon mileage')!, dueSoonDays: numericInput(days, 'Due-soon days', 3650)! } }; validateDocument(next); await onSave(next); common.onClose(); } catch(e) { setError((e as Error).message); } }
  return <Modal title="Vehicle & reminder preferences" {...common}><form onSubmit={submit}><fieldset disabled={common.busy}><div className="form-grid"><label>Make<input required maxLength={100} value={v.make} onChange={e => setV({ ...v, make: e.target.value })} /></label><label>Model<input required maxLength={100} value={v.model} onChange={e => setV({ ...v, model: e.target.value })} /></label><label>Year<input required type="number" min="1900" max={new Date().getFullYear() + 1} value={year} onChange={e => setYear(e.target.value)} /></label><label>Fuel type<select value={v.fuel} onChange={e => setV({ ...v, fuel: e.target.value })}><option value="">Not specified</option>{['Petrol', 'Diesel', 'Hybrid', 'Electric', 'Other'].map(f => <option key={f}>{f}</option>)}</select></label></div><label>Engine / variant<input maxLength={100} value={v.engine} placeholder="Optional, e.g. 2.4L" onChange={e => setV({ ...v, engine: e.target.value })} /></label><h3>When to show “Due soon”</h3><p className="help">These are display thresholds, not maintenance intervals.</p><div className="form-grid"><label>Within (km)<input required type="number" min="0" max="5000000" value={km} onChange={e => setKm(e.target.value)} /></label><label>Within (days)<input required type="number" min="0" max="3650" value={days} onChange={e => setDays(e.target.value)} /></label></div></fieldset><ErrorMessage error={error} /><Buttons {...common} label="Save vehicle" /></form></Modal>;
}
